version: '3.0'

services:
  front:
    build: ./front
    container_name: front_blog
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./front:/usr/src/front
      - /usr/src/front/node_modules

  back:
    build: ./back
    container_name: back_blog
    depends_on:
      - mongo
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    restart: always
    links:
      - mongo
    volumes:
      - ./back:/usr/src/back
      - /usr/src/back/node_modules

  mongo:
    image: mongo
    container_name: mongo_blog
    ports:
    - "27017:27017"
    restart: always
    volumes:
      - ./dump/:/docker-entrypoint-initdb.d/

